version: '3.7'

services:
  react-app:
    # This service builds the React app using the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: arbia07/react-jenkins-docker-k8s:latest
    container_name: webserver
    ports:
      - "1234:80" # Maps port 80 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
    restart: always

